WebCero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = "main"

urlpatterns = [
	path('', views.index, name='home'),
        # Rutas para registro
        path('register/', views.register, name='register'),
        # Rutas para Login
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

        # Rutas para categorías
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.create_category, name='create_category'),
        path('categories/<int:category_id>/edit/', views.edit_category, name='edit_category'),
    path('categories/<int:category_id>/delete/', views.delete_category, name='delete_category'),
    
    # Rutas para productos
    path('products/', views.product_list, name='product_list'),
    path('products/create/', views.create_product, name='create_product'),
    path('products/<int:product_id>/edit/', views.edit_product, name='edit_product'),
    path('products/<int:product_id>/delete/', views.delete_product, name='delete_product'),
	# Rutas para review
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product/<int:product_id>/add_review/', views.add_review, name='add_review')
    ]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product_images/')  
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    comment = models.TextField()

    def __str__(self):
        return f'Review for {self.product.name}'
    
    

main/forms.py
from django import forms
from .models import Category, Product, Review
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.models import User 




#Formulario de categorias
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

#Formulario de productos
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'image', 'category']

#Formulario de comentarios
class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))

#Formulario de review
class ReviewForm(forms.Form):
    rating = forms.ChoiceField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], label='Calificación')
    comment = forms.CharField(widget=forms.Textarea, label='Comentario')

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields

    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        try:
            validate_password(password, self.instance)
        except forms.ValidationError as e:
            self.add_error('password1', e)
        return password

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Category, Product, Review
from .forms import CategoryForm, ProductForm,CustomUserCreationForm, CommentForm, ReviewForm





# Vista para crear una nueva cuenta o registrarse
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('main:home')  
    else:
        form = AuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})

#@login_required
def index(request):
    return render(request, 'main/index.html')

# Create your views here.
# Vista para crear una nueva categoría
def create_category(request):
    if request.method == 'POST':
        if 'cancel' in request.POST:
            # Redirige a la lista de productos en caso de cancelación
            return redirect('main:category_list')
        elif 'save' in request.POST:
            # Lógica para guardar el producto
            form = CategoryForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('main:category_list')

    else:
        form = CategoryForm()
    
    return render(request, 'main/create_category.html', {'form': form})

# Vista para editar una categoría existente
def edit_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    
    if request.method == 'POST':
        if 'delete' in request.POST:
            # Lógica para eliminar la categoría
            category.delete()
            return redirect('main:category_list')
        elif 'cancel' in request.POST:
            # Redirige a la lista de categorías en caso de cancelación
            return redirect('main:category_list')
        elif 'save' in request.POST:
            # Lógica para guardar la categoría
            form = CategoryForm(request.POST, instance=category)
            if form.is_valid():
                form.save()
                return redirect('main:category_list')
    else:
        form = CategoryForm(instance=category)
        
    return render(request, 'main/edit_category.html', {'form': form, 'category': category})

# Vista para eliminar una categoría
def delete_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    
    if request.method == 'POST':
        category.delete()
        return redirect('main:category_list')  # Redirigir a la lista de categorías
    
    return render(request, 'main/delete_category.html', {'category': category})

# Vista para ver la lista de categorías
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'main/category_list.html', {'categories': categories})

# Vista para crear un nuevo producto
def create_product(request):
    if request.method == 'POST':
        if 'cancel' in request.POST:
            # Redirige a la lista de productos en caso de cancelación
            return redirect('main:product_list')
        elif 'save' in request.POST:
            # Lógica para guardar el producto
            form = ProductForm(request.POST, request.FILES )
            if form.is_valid():
                form.save()
                return redirect('main:product_list')
    else:
        form = ProductForm()
    categories = Category.objects.all()  # Obtén todas las categorías
    return render(request, 'main/create_product.html', {'form': form, 'categories': categories})

# Vista para editar un producto existente
def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
        if 'delete' in request.POST:
            # Lógica para eliminar el producto
            product.delete()
            return redirect('main:product_list')
        elif 'cancel' in request.POST:
            # Redirige a la lista de productos en caso de cancelación
            return redirect('main:product_list')
        elif 'save' in request.POST:
            # Lógica para guardar el producto
            form = ProductForm(request.POST,request.FILES, instance=product)
            if form.is_valid():
                form.save()
                return redirect('main:product_list')
    else:
        form = ProductForm(instance=product)
        
    categories = Category.objects.all()  # Obtén todas las categorías
    return render(request, 'main/edit_product.html', {'form': form, 'product': product, 'categories': categories})

# Vista para eliminar un producto
def delete_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
        product.delete()
        return redirect('main:product_list')  # Redirigir a la lista de productos
    
    return render(request, 'main/delete_product.html', {'product': product})

# Vista para ver la lista de productos
def product_list(request):
    # Obtén todas las categorías para construir el menú desplegable
    categories = Category.objects.all()

    # Inicializa una variable para almacenar la categoría seleccionada (por defecto, ninguna)
    selected_category_id = None
    selected_category_name = "Todos"  # Nombre por defecto para el botón

    if request.method == 'GET':
        # Obtiene el ID de la categoría seleccionada del formulario
        selected_category_id = request.GET.get('category')
        # Si se selecciona una categoría, obtén su nombre
        if selected_category_id:
            selected_category = Category.objects.get(id=selected_category_id)
            selected_category_name = selected_category.name

    # Filtra los productos según la categoría seleccionada (si hay alguna)
    if selected_category_id:
        products = Product.objects.filter(category_id=selected_category_id)
    else:
        # Si no se selecciona ninguna categoría, muestra todos los productos
        products = Product.objects.all()

    return render(request, 'main/product_list.html', {
        'products': products,
        'categories': categories,
        'selected_category_id': selected_category_id,
        'selected_category_name': selected_category_name  # Agregamos el nombre de la categoría seleccionada
    })
    
from .forms import CommentForm

# Vista para ver los detalles de los productos
def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    reviews = Review.objects.filter(product=product)

    return render(request, 'main/product_detail.html', {
        'product': product,
        'reviews': reviews,
    })

# Vista para agregar una review
@login_required
def add_review(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data['comment']
            rating = form.cleaned_data['rating']

            # Obtén el nombre de usuario del usuario actual
            user_name = request.user.username

            # Crea la revisión y asigna el nombre de usuario
            review = Review.objects.create(product=product, user=request.user, comment=comment, rating=rating)

            return redirect('main:product_detail', product_id=product_id)
    else:
        form = ReviewForm()

    return render(request, 'main/add_review.html', {'product': product, 'form': form})

main/templates/main/partials/footer.html
{% load static %}
<!--  ================================
Start Footer
=================================  -->
<footer>
  <div class="footerCol">
    <div class="container">
      <ul class="socialCol">
        <li>
          <a href="javascript:void(0)"><img src="{% static 'images/fb.svg' %}" alt="..." /></a>
        </li>
        <li>
          <a href="javascript:void(0)"><img src="{% static 'images/insta.svg' %}" alt="..." /></a>
        </li>
        <li>
          <a href="javascript:void(0)"><img src="{% static 'images/twitter.svg' %}" alt="..." /></a>
        </li>
        <li>
          <a href="javascript:void(0)"><img src="{% static 'images/linkedin.svg' %}" alt="..." /></a>
        </li>
      </ul>
      <div class="copyrightCol">
        <p>
          Copyright ©{% now 'Y' %}All rights reserved. Designed by <a href="https://jamesgrangerdesign.co.uk/" target="_blank">Designer</a>
        </p>
      </div>
    </div>
  </div>
</footer>
<!--  ================================
End Footer
=================================  -->

main/templates/main/partials/nav.html
{% load static %}
<!--  ================================
Start Navigation Bar
=================================  -->
<body>
  <header>
    <div class="headerCol">
      <div class="container-fluid">
        <div class="row align-items-center">
          <div class="col-auto">
            <div class="logoCol">
              <a href="{% url 'main:home' %}"><img src="{% static 'images/Logo.png' %}" alt="..." /></a>
            </div>
          </div>
          <div class="col">
            <div class="d-md-none">
              <button class="navToggle"><span class="navToggle__text">Toggle Menu</span></button>
            </div>
            <div class="navCollapseCol">
              <div class="navCol">
                <ul style="font-family: 'Chivo Mono', monospace;">
                  <li>
                    <a href="{% url 'main:home' %}">Home</a>
                  </li>
                  <li>
                    <a href="{% url 'main:product_list' %}">Productos</a>
                  </li>
                  {% if user.is_authenticated %}
                    <li>
                      <a href="{% url 'main:logout' %}">Cerrar sesión</a>
                    </li>
                  {% else %}
                    <li>
                      <a href="{% url 'main:login' %}">Iniciar sesión</a>
                    </li>
                    <li>
                      <a href="{% url 'main:register' %}">Registrarse</a>
                    </li>
                  {% endif %}
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
  <style>
    ul li {
      list-style: none;
    }
    ul li a {
      font-size: 26px;
      font-weight: 700;
      text-decoration: none;
      text-transform: uppercase;
      color: #343a40;
      padding: 10px;
      transition: 0.5s ease;
    }
    ul:hover li a {
      color: #30edf4;
    }
    ul:hover li a:not(:hover) {
      color: #343a40;
      opacity: 0.3;
      filter: blur(1px);
    }
  </style>
</body>
<!--  ================================
End Navigation Bar
=================================  -->