WebCero/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace='main')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views



app_name = "main"

urlpatterns = [
	path('', views.index, name='home'),
        # Rutas para registro
        path('register/', views.register, name='register'),
        # Rutas para Login
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

        # Rutas para categorías
    path('categories/', views.category_list, name='category_list'),
    path('categories/create/', views.create_category, name='create_category'),
        path('categories/<int:category_id>/edit/', views.edit_category, name='edit_category'),
    path('categories/<int:category_id>/delete/', views.delete_category, name='delete_category'),
    
    # Rutas para productos
    path('products/', views.product_list, name='product_list'),
    path('products/create/', views.create_product, name='create_product'),
    path('products/<int:product_id>/edit/', views.edit_product, name='edit_product'),
    path('products/<int:product_id>/delete/', views.delete_product, name='delete_product'),
	# Rutas para review
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('product/<int:product_id>/add_review/', views.add_review, name='add_review')
    ]

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.TextField()
    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='product_images/')  
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    
class Review(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])
    comment = models.TextField()

    def __str__(self):
        return f'Review for {self.product.name}'
    
    

main/forms.py
from django import forms
from .models import Category, Product, Review
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.password_validation import validate_password
from django.contrib.auth.models import User 




#Formulario de categorias
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name', 'description']

#Formulario de productos
class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['name', 'description', 'price', 'image', 'category']

#Formulario de comentarios
class CommentForm(forms.Form):
    comment = forms.CharField(widget=forms.Textarea(attrs={'rows': 4}))

#Formulario de review
class ReviewForm(forms.Form):
    rating = forms.ChoiceField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], label='Calificación')
    comment = forms.CharField(widget=forms.Textarea, label='Comentario')

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = UserCreationForm.Meta.fields

    def clean_password1(self):
        password = self.cleaned_data.get("password1")
        try:
            validate_password(password, self.instance)
        except forms.ValidationError as e:
            self.add_error('password1', e)
        return password

main/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .models import Category, Product, Review
from .forms import CategoryForm, ProductForm,CustomUserCreationForm, CommentForm, ReviewForm





# Vista para crear una nueva cuenta o registrarse
def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('main:home')
    else:
        form = CustomUserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            login(request, form.get_user())
            return redirect('main:home')  
    else:
        form = AuthenticationForm()

    return render(request, 'registration/login.html', {'form': form})

#@login_required
def index(request):
    return render(request, 'main/index.html')

# Create your views here.
# Vista para crear una nueva categoría
def create_category(request):
    if request.method == 'POST':
        if 'cancel' in request.POST:
            # Redirige a la lista de productos en caso de cancelación
            return redirect('main:category_list')
        elif 'save' in request.POST:
            # Lógica para guardar el producto
            form = CategoryForm(request.POST)
            if form.is_valid():
                form.save()
                return redirect('main:category_list')

    else:
        form = CategoryForm()
    
    return render(request, 'main/create_category.html', {'form': form})

# Vista para editar una categoría existente
def edit_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    
    if request.method == 'POST':
        if 'delete' in request.POST:
            # Lógica para eliminar la categoría
            category.delete()
            return redirect('main:category_list')
        elif 'cancel' in request.POST:
            # Redirige a la lista de categorías en caso de cancelación
            return redirect('main:category_list')
        elif 'save' in request.POST:
            # Lógica para guardar la categoría
            form = CategoryForm(request.POST, instance=category)
            if form.is_valid():
                form.save()
                return redirect('main:category_list')
    else:
        form = CategoryForm(instance=category)
        
    return render(request, 'main/edit_category.html', {'form': form, 'category': category})

# Vista para eliminar una categoría
def delete_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    
    if request.method == 'POST':
        category.delete()
        return redirect('main:category_list')  # Redirigir a la lista de categorías
    
    return render(request, 'main/delete_category.html', {'category': category})

# Vista para ver la lista de categorías
def category_list(request):
    categories = Category.objects.all()
    return render(request, 'main/category_list.html', {'categories': categories})

# Vista para crear un nuevo producto
def create_product(request):
    if request.method == 'POST':
        if 'cancel' in request.POST:
            # Redirige a la lista de productos en caso de cancelación
            return redirect('main:product_list')
        elif 'save' in request.POST:
            # Lógica para guardar el producto
            form = ProductForm(request.POST, request.FILES )
            if form.is_valid():
                form.save()
                return redirect('main:product_list')
    else:
        form = ProductForm()
    categories = Category.objects.all()  # Obtén todas las categorías
    return render(request, 'main/create_product.html', {'form': form, 'categories': categories})

# Vista para editar un producto existente
def edit_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
        if 'delete' in request.POST:
            # Lógica para eliminar el producto
            product.delete()
            return redirect('main:product_list')
        elif 'cancel' in request.POST:
            # Redirige a la lista de productos en caso de cancelación
            return redirect('main:product_list')
        elif 'save' in request.POST:
            # Lógica para guardar el producto
            form = ProductForm(request.POST,request.FILES, instance=product)
            if form.is_valid():
                form.save()
                return redirect('main:product_list')
    else:
        form = ProductForm(instance=product)
        
    categories = Category.objects.all()  # Obtén todas las categorías
    return render(request, 'main/edit_product.html', {'form': form, 'product': product, 'categories': categories})

# Vista para eliminar un producto
def delete_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    
    if request.method == 'POST':
        product.delete()
        return redirect('main:product_list')  # Redirigir a la lista de productos
    
    return render(request, 'main/delete_product.html', {'product': product})

# Vista para ver la lista de productos
def product_list(request):
    # Obtén todas las categorías para construir el menú desplegable
    categories = Category.objects.all()

    # Inicializa una variable para almacenar la categoría seleccionada (por defecto, ninguna)
    selected_category_id = None
    selected_category_name = "Todos"  # Nombre por defecto para el botón

    if request.method == 'GET':
        # Obtiene el ID de la categoría seleccionada del formulario
        selected_category_id = request.GET.get('category')
        # Si se selecciona una categoría, obtén su nombre
        if selected_category_id:
            selected_category = Category.objects.get(id=selected_category_id)
            selected_category_name = selected_category.name

    # Filtra los productos según la categoría seleccionada (si hay alguna)
    if selected_category_id:
        products = Product.objects.filter(category_id=selected_category_id)
    else:
        # Si no se selecciona ninguna categoría, muestra todos los productos
        products = Product.objects.all()

    return render(request, 'main/product_list.html', {
        'products': products,
        'categories': categories,
        'selected_category_id': selected_category_id,
        'selected_category_name': selected_category_name  # Agregamos el nombre de la categoría seleccionada
    })
    
from .forms import CommentForm

# Vista para ver los detalles de los productos
def product_detail(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    reviews = Review.objects.filter(product=product)

    return render(request, 'main/product_detail.html', {
        'product': product,
        'reviews': reviews,
    })

# Vista para agregar una review
@login_required
def add_review(request, product_id):
    product = get_object_or_404(Product, pk=product_id)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            comment = form.cleaned_data['comment']
            rating = form.cleaned_data['rating']

            # Obtén el nombre de usuario del usuario actual
            user_name = request.user.username

            # Crea la revisión y asigna el nombre de usuario
            review = Review.objects.create(product=product, user=request.user, comment=comment, rating=rating)

            return redirect('main:product_detail', product_id=product_id)
    else:
        form = ReviewForm()

    return render(request, 'main/add_review.html', {'product': product, 'form': form})

main/templates/main/add_review.html
{% extends 'main/base.html' %}
{% load static %}

{% block title %}
  Detalles del Producto
{% endblock %}
{% block description %}
  Detalles del producto seleccionado
{% endblock %}
{% block keywords %}
  producto, detalles, revisión, opiniones
{% endblock %}

{% block extend_header %}
  <style>
    /* Agregar estilos personalizados aquí si es necesario */
    .review-form {
      max-width: 500px;
      margin: 0 auto;
    }

    .review-form label {
      font-weight: bold;
    }

    .review-form .form-group {
      margin-bottom: 20px;
    }

    .review-form .btn-primary {
      background-color: #007BFF;
      border: none;
    }
  </style>
{% endblock %}

{% block extend_footer %}
  <script>
    // Agregar scripts personalizados aquí si es necesario
  </script>
{% endblock %}

{% block content %}
  <div class="container">
    <h1>Opiniones de {{ product.name }}</h1>
    <div class="reviews">
      {% for review in product.reviews.all %}
        <div class="review">
          <h3>Calificación: {{ review.rating }}</h3>
          <p>{{ review.comment }}</p>
        </div>
      {% endfor %}
    </div>
    
    <h2>Dejar una reseña</h2>
    <form method="post" class="review-form">
      {% csrf_token %}
      {{ form.non_field_errors }}
      <div class="form-group">
        <label for="{{ form.rating.id_for_label }}">Calificación:</label>
        {{ form.rating }}
        {{ form.rating.errors }}
      </div>
      <div class="form-group">
        <label for="{{ form.comment.id_for_label }}">Comentario:</label>
        {{ form.comment }}
        {{ form.comment.errors }}
      </div>
      <button type="submit" class="btn btn-primary">Enviar Reseña</button>
    </form>
  </div>
{% endblock %}

main/templates/main/category_list.html
{% extends 'main/base.html' %}
{% load static %}

<!-- ================================
Start SEO blocks
================================= -->
{% block title %}Listado de Categorías{% endblock %}
{% block description %}Lista de todas las categorías disponibles{% endblock %}
{% block keywords %}categorías, productos{% endblock %}
<!-- ================================
END SEO blocks
================================= -->

<!-- ================================
Start CSS blocks
================================= -->
{% block extend_header %}
<style>
  /* Estilo para la lista de categorías */
  ul.category-list {
    list-style: none;
    padding: 0;
  }

  ul.category-list li {
    margin-bottom: 10px;
    font-size: 18px; /* Tamaño de fuente deseado */
  }

  ul.category-list li a {
    text-decoration: none;
    color: #0000A0; /* Cambia este valor al color deseado */
  }

  ul.category-list li a:hover {
    text-decoration: underline; /* Subrayar al pasar el mouse */
  }
</style>
{% endblock %}
<!-- ================================
END CSS blocks
================================= -->

<!-- ================================
Start script blocks
================================= -->
{% block extend_footer %}{% endblock %}
<!-- ================================
END script blocks
================================= -->

<!-- ================================
Start Content
================================= -->
{% block content %}
  <body>
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <!-- Centra el título -->
          <div class="row g-4 g-md-3 align-items-center">
            <div class="col-md-8">
              <!-- Le da un salto de línea al título si es largo -->
              <div class="bannerContent">
                <h1 class="xlTitle pb-md-3" style="font-size: 78px; font-family: Lovelyn;">Categorías</h1>
                <ul class="category-list">
                  {% for category in categories %}
                    <li><a href="{% url 'main:edit_category' category.id %}">{{ category.name }}</a> - 
                      {{ category.description|truncatechars:40 }} <!-- Tamaño de la descripción -->
                    </li>
                  {% endfor %}
                </ul>
                <a href="{% url 'main:create_category' %}" class="btn btn-primary position-fixed bottom-0 end-0 m-3">Crear Nueva Categoría</a>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
  <!-- Ver cómo incorporar esto -->
  <!-- ================================
  End Content
  ================================== -->
{% endblock %}

main/templates/main/delete_category.html
{% extends 'main/base.html' %}
{% load static %}

<!-- Resto de bloques SEO, CSS, y script -->

{% block content %}
  <section>
    <div class="innerPageBannerCol">
      <div class="container">
        <div class="row g-4 g-md-3 align-items-center">
          <div class="col-md-6">
            <div class="bannerContent">
              <h1 class="xlTitle pb-md-3" style="font-size: 78px; font-family: Lovelyn;">Confirmar Eliminación de Categoría</h1>
              <p>¿Estás seguro de que deseas eliminar la categoría "{{ category.name }}"?</p>
              <form method="post">
                {% csrf_token %}
                <input type="submit" value="Eliminar" />
              </form>
              <a href="{% url 'main:category_list' %}">Cancelar</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
{% endblock %}

main/templates/main/product_detail.html
{% extends 'main/base.html' %}
{% load static %}

<!--    ================================
Start SEO blocks
=================================    -->
{% block title %}
  Listado de Categorías
{% endblock %}
{% block description %}
  Lista de todas las categorías disponibles
{% endblock %}
{% block keywords %}
  categorías, productos
{% endblock %}
<!--    ================================
END SEO blocks
=================================    -->

<!--    ================================
Start CSS blocks
=================================    -->
{% block extend_header %}
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <style>
    /* Estilo para la lista de categorías */
    ul.category-list {
      list-style: none;
      padding: 0;
    }
    
    ul.category-list li {
      margin-bottom: 10px;
      font-size: 18px; /* Tamaño de fuente deseado */
    }
    
    ul.category-list li a {
      text-decoration: none;
      color: #0000a0; /* color deseado */
    }
    
    ul.category-list li a:hover {
      text-decoration: underline; /* Subrayar al pasar el mouse */
    }
    
    /* Estilo para el contenedor de detalles del producto */
    .product-details-container {
      display: flex;
      align-items: center;
    }
    
    .product-image {
      width: 240px;
      height: 240px;
      background-color: #f0f0f0; /* Fondo gris-blanco */
      display: flex;
      justify-content: center;
      align-items: center;
      border: 1px solid #ccc;
      margin-right: 20px;
    }
    
    .product-details {
      flex: 1;
    }
    
    .product-name {
      font-size: 24px; /* Tamaño de fuente para el nombre del producto */
    }
    
    .product-description {
      font-size: 18px; /* Tamaño de fuente para la descripción */
    }
    
    .product-price {
      font-size: 20px; /* Tamaño de fuente para el precio */
    }
  </style>
{% endblock %}
<!--    ================================
END CSS blocks
=================================    -->

<!--    ================================
Start script blocks
=================================    -->
{% block extend_footer %}
  <link rel="stylesheet" type="text/css" href="{% static 'MiniProyecto#2/static/starability-master' %}" />
  <script src="{% static 'MiniProyecto#2/static/starability-master' %}"></script>
{% endblock %}
<!--    ================================
END script blocks
=================================    -->

<!--    ================================
Start Content
=================================    -->
{% block content %}
  <body>
    <section>
      <div class="innerPageBannerCol">
        <div class="container">
          <!-- centra el titulo -->
          <div class="row g-4 g-md-3 align-items-center">
            <div class="col-md-10">
              <!-- le da un salto de linea al titulo si es largo -->
              <div class="bannerContent">
                <div class="container">
                  <div class="row">
                    <div class="col-md-2">
                      <!-- Columna para el logotipo -->
                      <div class="logoCol">
                        <img src="{% static 'images/logoi.png' %}" alt="Logo" style="max-width: 80%; max-height: 80%;" />
                      </div>
                    </div>
                    <div class="col-md-10">
                      <!-- Columna para el título -->
                      <h1 class="xlTitle pb-md-5" style="font-size: 100px; font-family: Lovelyn;">Detalles:</h1>
                    </div>
                  </div>
                </div>
                <div class="container">
                  <div class="product-details-container">
                    <div class="product-image">
                      <img src="{{ product.image.url }}" alt="{{ product.name }}" style="max-width: 100%; max-height: 100%;" />
                    </div>
                    <div class="product-details">
                      <h2 class="product-name">{{ product.name }}</h2>
                      <p class="product-description">{{ product.description }}</p>
                      <p class="product-price">
                        <strong>Precio: ${{ product.price }}</strong>
                      </p>
                    </div>
                  </div>
                  <h1>Reviews:</h1>
                  <ul>
                    {% for review in reviews %}
                      <li>
                        <strong>{{ review.user.username }}:</strong>
                        <p>{{ review.comment }}</p>
                        <p>Rating: {{ review.rating }}/5</p>
                      </li>
                      {% empty %}
                      <li>No hay reseñas para este producto.</li>
                    {% endfor %}
                  </ul>
                  <!-- Agregar un formulario para que los usuarios dejen sus revisiones -->
                  <h3>Dejar una Reseña:</h3>
                  <form method="post" action="{% url 'main:add_review' product.id %}">
                    {% csrf_token %}
                    <label for="comment">Comentario:</label>
                    <textarea name="comment" required></textarea>
                    <label for="rating">Puntuación (1-5):</label>
                    <input type="hidden" name="rating" id="rating" required />
                    <div>
                      <input type="radio" id="1-star" name="rating" value="1" />
                      <label for="1-star" title="Muy malo"><i class="fas fa-star"></i></label>
                    
                      <input type="radio" id="2-stars" name="rating" value="2" />
                      <label for="2-stars" title="Malo"><i class="fas fa-star"></i></label>
                    
                      <input type="radio" id="3-stars" name="rating" value="3" />
                      <label for="3-stars" title="Promedio"><i class="fas fa-star"></i></label>
                    
                      <input type="radio" id="4-stars" name="rating" value="4" />
                      <label for="4-stars" title="Bueno"><i class="fas fa-star"></i></label>
                    
                      <input type="radio" id="5-stars" name="rating" value="5" />
                      <label for="5-stars" title="Excelente"><i class="fas fa-star"></i></label>
                    </div>
                    
                    <button type="submit">Enviar Reseña</button>
                  </form>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </body>
  <!-- ver como incorporar esto -->
  <!--    ================================
End Content
=================================    -->
{% endblock %}

main/templates/main/product_list.html
{% extends 'main/base.html' %}
{% load static %}

<!--   ================================
Start SEO blocks
=================================   -->
{% block title %}
  Listado de Productos
{% endblock %}
{% block description %}
  Lista de todos los productos disponibles
{% endblock %}
{% block keywords %}
  productos, categorías
{% endblock %}
<!--   ================================
END SEO blocks
=================================   -->

<!--   ================================
Start CSS blocks
=================================   -->
{% block extend_header %}
  <style>
    .product-container {
      display: flex;
      justify-content: space-between;
      align-items: center;
      border: 1px solid #ccc;
      padding: 10px;
      margin-bottom: 10px;
      background-color: white;
      height: 100%;
    }
    
    .product-image {
      width: 240px;
      height: 240px;
      background-color: #f0f0f0; /* Fondo gris-blanco */
      display: flex;
      justify-content: center;
      align-items: center;
      border: 1px solid #ccc;
    }
    
    .product-details {
      flex: 1;
      padding-left: 10px;
    }
    
    /* Estilos para el botón Categorías */
    .category-button {
      background-color: #007bff;
      color: #fff;
      padding: 5px 10px; /* Ajustar el espaciado interno */
      border: none;
      cursor: pointer;
      margin-bottom: 10px; /* Separar el botón del primer producto */
      width: 120px; /* Ancho automático para el botón */
      text-align: center; /* Centrar el texto en el botón */
    }
    
    /* Estilos para el menú de categorías */
    .category-menu {
      display: none;
      position: absolute;
      background-color: white;
      border: 1px solid #ccc;
      border-radius: 4px;
      margin-top: 5px;
      min-width: 90px; /* Ajustar el ancho mínimo */
      text-align: left; /* Alinear el texto a la izquierda */
    }
    
    .category-button:hover + .category-menu,
    .category-menu:hover {
      display: block;
    }
    
    .category-menu a {
      display: block;
      padding: 8px 12px;
      text-decoration: none;
      color: #333;
    }
    
    .category-menu a:hover {
      background-color: #f0f0f0;
    }
    
    /* Estilos para alinear los productos a la derecha */
    .product-list {
      margin-left: auto;
      margin-right: 0;
    }
  </style>
{% endblock %}
<!--   ================================

END CSS blocks
=================================   -->

<!--   ================================
Start script blocks
=================================   -->
{% block extend_footer %}
  <script>
    document.addEventListener('DOMContentLoaded', function () {
      const categoryButton = document.querySelector('.category-button')
      const categoryMenu = document.querySelector('.category-menu')
    
      categoryButton.addEventListener('click', function () {
        categoryMenu.style.display = categoryMenu.style.display === 'block' ? 'none' : 'block'
      })
    
      document.addEventListener('click', function (event) {
        if (!categoryButton.contains(event.target) && !categoryMenu.contains(event.target)) {
          categoryMenu.style.display = 'none'
        }
      })
    })
  </script>
{% endblock %}
<!--   ================================
END script blocks
=================================   -->

<!--   ================================
Start Content
=================================   -->
{% block content %}
  <body>
    
    <section>
      <div class="innerPageBannerCol">
        <!-- Centro vertical -->
        <div class="container">
          <!-- Centro horizontal -->
          <div class="row g-4 g-md-3 align-items-center">
            <div class="col-md-12">
              <div class="bannerContent">
                <div class="container">
                    <div class="row">
                        <div class="col-md-2">
                            <!-- Columna para el logotipo -->
                            <div class="logoCol">
                                <img src="{% static 'images/logoi.png' %}" alt="Logo" style="max-width: 80%; max-height: 80%;" />
                            </div>
                        </div>
                        <div class="col-md-10">
                            <!-- Columna para el título -->
                            <h1 class="xlTitle pb-md-5" style="font-size: 100px; font-family: Lovelyn;">Productos</h1>
                        </div>
                    </div>
                </div>
                <!-- formulario de filtro por categoría -->
                <div class="dropdown">
                  <a class="btn btn-secondary dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Categoría: {{ selected_category_name }}
                  </a>
                
                  <ul class="dropdown-menu">
                    <li><a class="dropdown-item" href="{% url 'main:product_list' %}">Todos</a></li>
                    {% for category in categories %}
                      <li><a class="dropdown-item" href="{% url 'main:product_list' %}?category={{ category.id }}">{{ category.name }}</a></li>
                    {% endfor %}
                  </ul>
                </div>
                <div class="product-list">
                  {% for product in products %}
                    <a href="{% url 'main:product_detail' product.id %}" style="text-decoration: none; color: inherit;">
                      <div class="product-container">
                        <div class="product-image">
                          {% if product.image %}
                            <img src="{{ product.image.url }}" alt="{{ product.name }}" style="max-width: 100%; max-height: 100%;" />
                          {% else %}
                            <p>Imagen no disponible</p>
                          {% endif %}
                        </div>
                        <div class="product-details">
                          <h2>{{ product.name }}</h2>
                          <p>{{ product.description|truncatechars:100 }}</p>
                          <p>
                            <strong>Precio: ${{ product.price }}</strong>
                          </p>
                          <a href="{% url 'main:edit_product' product.id %}"><i class="fas fa-pencil-alt"></i> Editar</a>
                        </div>
                      </div>
                    </a>
                  {% endfor %}
                </div>
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  <!-- Botones Inferiores -->
  <a href="{% url 'main:category_list' %}" class="btn btn-primary position-fixed bottom-0 start-0 m-3">Editar Categorías</a>
  <a href="{% url 'main:create_product' %}" class="btn btn-primary position-fixed bottom-0 end-0 m-3">Crear Producto</a>
  </body>
  <!-- ver como incorporar esto -->
  <!--   ================================
End Content
=================================   -->
{% endblock %}